# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: mixed-line-ending
    args: [--fix=lf]
    # YAML specific
  - id: check-yaml
  - id: check-merge-conflict
    # TOML specific
  - id: check-toml
    # Markdown specific
  - id: check-case-conflict
  - id: fix-byte-order-marker
    # Other useful checks
  - id: detect-private-key
  - id: debug-statements

# YAML specific
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']



# Markdown specific
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.39.0
  hooks:
  - id: markdownlint
    args: [--fix, --disable, line-length, --ignore, MD013, --ignore, MD036]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [--profile, black, --line-length, '99']

- repo: https://github.com/psf/black
  rev: 24.1.1
  hooks:
  - id: black
    language_version: python3.11
    args: [--line-length, '99']

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
  - id: ruff
    args: [--fix, --line-length=99]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests        # Add only the type stubs you need
    args: [--ignore-missing-imports, --check-untyped-defs]
