[tool.black]
line-length = 99
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 99

[tool.ruff]
lint.select = ["E", "F", "B"]
lint.ignore = []
line-length = 99
